name: Mis à jour index.json - auto

on:
  pull_request:
    branches:
      - main

jobs:
  maj-index:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    if: github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - name: Vérification du repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Installation de python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Installation des dépendances
        run: pip install requests

      - name: Lancement des scripts
        run: python .github/scripts/index.py

      - name: Ajout des changements (commit)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add index.json

          git diff --cached --quiet && exit 0

          git commit -m "chore: update index.json"

          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git

          git push origin HEAD:${{ github.head_ref }}